spring:
  profiles:
    active: secret
  application:
    name: server
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    check-template-location: true
  data:
    redis:
      host: localhost
      port: 6379
