spring:
  profiles:
    active: secret
  application:
    name: server
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    check-template-location: true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coaster
    username: user
    password: root