spring:
  application:
    name: server
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    check-template-location: true
  data:
    redis:
      port: 6379